baseURL = '/'
languageCode = 'en-us'
title = 'Linus Kübler'
theme = 'minimal'

[params]
  description = 'Personal website'
  author = 'Linus Kübler'
  email = 'kuebler.linus+contact@gmail.com'
  linkedin = 'https://www.linkedin.com/in/lkuebler/'
  github = 'https://github.com/lkuebler'
  profile_image = 'images/profile.png'
